# Source Database Configuration
source:
  environment: development
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: postgres

# Destination Database Configuration
destination:
  environment: production
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: postgres

# Table Configuration
table:
  migration_log:
    table_name: tbl_migration_log
    table_schema: public
  migration_activity:
    table_name: tbl_migration_activity
    table_schema: public